### ISSUE TITLE
BeardDBTable are usually instance variables but are shared across instances

### ISSUE THREAD

**Issue by nasfarley88** [LanceMaverick/skybeard-2#104]
At the moment, the recommended use for `BeardDBTable` is as an instance variable, but the database table is shared by all instances of the *class* rather than being individual to every *instance* (as one would expect an instance variable to be). 

I think there is a case for having both a table for the class, and a table for each instance, but I'm wondering about implementation.

Two classes? A keyword bool argument (e.g. `per_instance=True/False`? `shared_between_instances=True/False`)? What are people's feelings?

**Comment by LanceMaverick** [comment]
I think separate classes are the best way to go as it's more explicit. Could inherit from the same class, just the table name being the only difference?

**Comment by nasfarley88** [comment]
Agreed, `BeardDBTable` and `BeardInstanceDBTable`?

**Comment by LanceMaverick** [comment]
Sounds good!
