### ISSUE TITLE
Make beard packaging system?

### ISSUE THREAD

**Issue by nasfarley88** [LanceMaverick/skybeard-2#111]
I propose a simple script to use as a 'pip for beards'. This would require two things:

1) Yaml files for each available beard. Something simple like:
```yaml
name: Postcats
git: https://github.com/LanceMaverick/postcats-beard
```
for each bear.

2) a script to get the beards. This would be a simple python script which reads the yaml, reads it's first argument and downloads the beard. There could even be an update mechanism for the beards.

This issue goes towards fulfilling #62

**Comment by LanceMaverick** [comment]
Was this fulfilled with #114 ?

**Comment by nasfarley88** [comment]
I would say yes.
