### ISSUE TITLE
Add Skybeard-2 to CircleCI for Continuous Integration

### ISSUE THREAD

**Issue by artemis-beta** [LanceMaverick/skybeard-2#142]
With skybeard-2 added to CircleCI there will be no need for manual "nightlies", tests will be run automatically whenever a new commit/merge request is made. Further to this the API means results will be forwarded to a new 'devbeard' which will show the latest results.

**Comment by LanceMaverick** [comment]
Done. Working tox and circle configuration files merged into skb-dev and master branches.
