### ISSUE TITLE
Skybeard 2.1 tagged release?

### ISSUE THREAD

**Issue by nasfarley88** [LanceMaverick/skybeard-2#61]
I feel like we are getting to the stage where we can feature freeze the core skybeard features for a tagged 2.1 release. Any thoughts?

**Comment by LanceMaverick** [comment]
The current master can be tagged as v2.1

**Comment by nasfarley88** [comment]
Do we want to include the new docs in 2.1?

**Comment by LanceMaverick** [comment]
Yep!

**Comment by nasfarley88** [comment]
We are now tagged!

**Comment by LanceMaverick** [comment]
Tagged and released [Skybeard v2.1](https://github.com/LanceMaverick/skybeard-2/releases)
