### ISSUE TITLE
NatRailPlugin: Case Sensitivity

### ISSUE THREAD

**Issue by artemis-beta** [LanceMaverick/skybeard-2#71]
Correct issue where currently stations have to be exact in terms of case, e.g.:
`/departures selly oak`
raises an error:
`/departures Selly Oak`
works correctly.

**Comment by LanceMaverick** [comment]
Fixed by ensuring title case on arguments to natrailreq commands

**Comment by artemis-beta** [comment]
The global fix you applied is best I feel, I just need to find a way of making exceptions for station codes
