### ISSUE TITLE
Suggested changes to natrailenq

### ISSUE THREAD

**Issue by LanceMaverick** [LanceMaverick/skybeard-2#74]
# Current known issues are:

- Case issue: 
    - Case of station names needs to be matched exactly for it to be found.
    - Ensuring title case does not work with all stations (e.g. hyphenated)
    - Ensuring title case means codes do not work
    - Making codes also case independent gives partial matched also for station names
- Error handling:
    - Currently difficult to debug due to no intermediate validations, only throwing an exception at the end and result is empty.
- Long messages:
    - Some departure boards are longer than the character limit for telegram bot messages. 

# Changing station code storage
Case issues due to how data is stored. json object in which keys are station names and the values. Don't get much flexibility with key matching. Could be better to store data as list of dictionaries.
json can be converted to this with:
```Python
self.codes = [dict(station = k, code = v)
                         for k, v in json_codes.items()]
```
Then, stations and codes can be searched at the same time like so:
```Python
def find_match(self, query):
    for item in self.codes:
        station = item['station'].lower()
        code = item['code']
        if station == query.lower() or code = query:
            return item['code']
```
This will return the code of a station if either the station name matches (case insensitive) or the station code matches (case sensitive, user must send it in capitals - best practice in my opinion).

# Error handling
It would be good to make the code throw exceptions at particular points, such as if no matches are found in the station code data, or no data is returned from the scrape. This would make it much easier to debug.

# PEP8
Not crucial but we try to keep all the skybeard code PEP8 compliant (camel case for classes but everything else underscores_and_lowercase, etc)
https://www.python.org/dev/peps/pep-0008/

Also 4 spaces for indents, no tabs. There's inconsistency at the moment, with class members indented with 6 spaces and lines within them indented by two?

**Comment by LanceMaverick** [comment]
What I forgot to mention is the handling of long messages. The utils function I made will solve this and will work like so:
```Python
from skybeard.utils import partition
message = some_function_that_returns_a_long_message()
split_message = partition_text(message)
for m in split_message:
    await self.sender.sendMessage(m)
```
If doesn't matter if the function returns a long or short message, as for a short enough message `partition_text(message)` will return `[message]`

**Comment by artemis-beta** [comment]
Moved to [`natrailenq` repo](https://github.com/artemis-beta/skb-natrailenq)
